<?php

namespace app\admin\controller;

use think\Controller;
use app\common\model\category;
class Article extends Controller
{

    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }


    /**
     * 文章首页
     */
    public function index(){
        $field = $this->db->getAll(1 );


        $this->assign( 'field' , $field );
        return $this->fetch();

    }

    /**
     * 添加文章
     */
    public function store(){


        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res){
                $this->success($res['msg'],'admin/article/index');
            }else{

                $this->error($res['msg']);
            }
        }

        //1.获取分类数据
        $cateData = ( new Category() )->getAll();
        $this->assign( 'cateData' , $cateData );
        //2.获取标签数据
        $tagData = db( 'tag' )->select();
        $this->assign( 'tagData' , $tagData );

        return $this->fetch();

    }

    /**
     * ajax修改文章排序
     */
    public function changesort(){

        if(request()->isAjax()){
            $result = $this->db->changesort(input('post.'));

            if($result['error']){

                $this->success($result['msg'],'index');die;
            }else{

                $this->error($result['msg']);die;
            }


        }


    }

    /**
     * 编辑文章
     */
    public function edit(){
        $arc_id = input('param.arc_id');

        if(request()->isPost()){

            $res = $this->db->edit(input('post.'));

            if($res){

                $this->success($res['msg'],'index');
            }else{

                $this->error($res['msg']);
            }
        }

        //1.获取分类数据
        $cateData = ( new Category() )->getAll();
        $this->assign( 'cateData' , $cateData );
        //2.获取标签数据
        $tagData = db('tag')->select();
        $this->assign( 'tagData' , $tagData );

        //3.获取旧数据
        $oldData = db('article')->where('arc_id',$arc_id)->find();
        $this->assign( 'oldData' , $oldData );

        //4.获取标签数据
        $tag_id = db( 'arc_tag' )->where('arc_id',$arc_id)->column('tag_id');
        $this->assign( 'tag_id' , $tag_id );


        return $this->fetch();




    }

    /**
     * 删除文章回收站
     */
    public function deltorecycle(){
        $arc_id = input('param.arc_id');
        $result = $this->db->save(['arc_recycle'=>2],['arc_id'=>$arc_id]);
        if($result){
            $this->success('回收成功','index');
        }else{
            $this->error('回收失败');
        }


    }

    /**
     * 恢复数据
     */
    public function outTorecycle(){
        $arc_id = input('param.arc_id');
        $result = $this->db->save(['arc_recycle'=>1],['arc_id'=>$arc_id]);
        if($result){
            $this->success('恢复成功','recycle');
        }else{
            $this->error('恢复失败');
        }

    }

    /**
     * 回收站管理
     */
    public function recycle(){
        $field = $this->db->getAll(2 );

        $this->assign( 'field' , $field );
        return $this->fetch();
    }

    /**
     * 彻底删除
     */
    public function del(){

        $arc_id = input('param.arc_id');
        $result = $this->db->del($arc_id);
        if($result){
            $this->success($result['msg'],'recycle');
        }else{

            $this->error($result['msg']);
        }
    }






}
