<?php

namespace app\admin\controller;

use think\Controller;
class Category extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->db = new \app\common\model\category();
    }


    /*
     * 栏目首页
     * */
    public function  index(){

        //$result = db('cate')->select();
        $result = $this->db->getAll();


        $this->assign('result',$result);
       return $this->fetch();

    }

    /*
     * 添加栏目
     * */
    public function add(){
        if(request()->isPost()) {
            $res = $this->db->add(input('post.'));
           if($res['error']){
               $this->error($res['msg']);

           }else{
               $this->success($res['msg'],'admin/category/index');
           }
        }
        return $this->fetch();

    }

    /*
     * 添加子级栏目
     * */
    public function addSon(){

        $cate_id = input('param.cate_id');
        $db  = $this->db->where('cate_id',$cate_id)->find();

        $this->assign('db',$db);
        return $this->fetch();
    }

    /**
     * @return mixed
     * 编辑栏目
     */
    public function edit(){


        if(request()->isPost()){

            $res = $this->db->edit(input('post.'));
            if($res){

                $this->success($res['msg'],'admin/category/index');
            }else{

                $this->error($res['msg']);
            }

        }

        $cate_id = input('param.cate_id');
        $userinfo = $this->db->find($cate_id);
        $this->assign('userinfo',$userinfo);


        //获取栏目分类（排除自己与父级id）
        $cate = $this->db->getCateData($cate_id);
        $this->assign('cate',$cate);


        return $this->fetch();
    }

    /**
     * 删除栏目
     */
    public function del(){
        $cate_id = input('param.cate_id');
        $res = $this->db->del($cate_id);
        if($res){

            $this->success($res['msg'],'admin/category/index');
        }else{

            $this->error($res['msg']);

        }

    }




}
