<?php

namespace app\admin\controller;

use think\Controller;

class Link extends Controller
{

    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Link();
    }

    /**
     *
     * 友情连接首页展示
     */
    public function index(){
        $data = $this->db->getAll();
        $this->assign('data',$data);
        return $this->fetch();
    }

    /**
     * 添加友链
     */
    public function add(){

        $link_id = input('param.link_id');


        if(request()->isPost()){

            $result = $this->db->add(input('post.'));
            if($result){
                $this->success($result['msg'],'index');
            }else{

                $this->error($result['msg']);
            }
        }

        if($link_id){

            $data = $this->db->find($link_id);
        }else{

            $data = ['link_name'=>'','link_url'=>'','link_sort'=>100];
        }

        $this->assign('data',$data);
        return $this->fetch();

    }

    /**
     * 删除友链
     */
    public function del(){

        $link_id = input('param.link_id');

        $result = $this->db->del($link_id);
        if($result['error']){

            $this->success($result['msg'],'index');

        }else{
            $this->error($result['msg']);

        }

    }



}
