<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{

    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }


    /**
     * 标签页展示
     */
    public function index(){
        // 查询标签数据 并且每页显示10条数据
        $list = Db('tag')->paginate(2);
        $this->assign('list',$list);
        return $this->fetch();
    }

    /**
     * 添加标签
     */
    public function add(){
        $tag_id = input('param.tag_id');

        if(request()->isPost()){

            $res = $this->db->add(input('post.'));

            if($res){
                $this->success($res['msg'],'admin/tag/index');
            }else{
                $this->error($res['msg']);
            }

        }

        if($tag_id){
           $oldData = $this->db->find($tag_id);


        }else{

            $oldData = array(
                'tag_name'=>'',
                'tag_id'=>''
            );

        }

        $this->assign('oldData',$oldData);




        return $this->fetch();

    }

    /**
     * 删除标签
     */
    public function del(){

        $tag_id = input('param.tag_id');
        $result =  \app\common\model\Tag::destroy($tag_id);
        if($result){

            $this->success('删除成功','admin/tag/index');

        }else{

            $this->error('删除失败');
        }

    }




}
